### ISSUE TITLE
Samsung Pay Supported check.

### ISSUE THREAD

**Issue by ahmermughal** [network-international/payment-sdk-android#12]
I am not able to find a way through this SDK to check if Samsung Pay is available on the device.

**Comment by mu1ex** [comment]
Hi @ahmermughal please use the following to find if Samsung Pay is supported
```kotlin
getSupportedPaymentMethods(listener: SupportedPaymentTypesListener)
``` 
Its available in this class [here](https://github.com/network-international/payment-sdk-android/blob/master/payment-sdk/src/main/java/payment/sdk/android/PaymentClient.kt#L33)
