### ISSUE TITLE
project is not runnig first i am facing this generated issue then comes build errors .i updated all sdk dependancy still same problem is occuring.

### ISSUE THREAD

**Issue by Tulsigohel** [network-international/payment-sdk-android#20]
package payment.sdk.android.demo;

import dagger.MembersInjector;
import javax.annotation.processing.Generated;
import javax.inject.Provider;
import payment.sdk.android.demo.dependency.configuration.Configuration;

@Generated(
  value = "dagger.internal.codegen.ComponentProcessor",
  comments = "https://google.github.io/dagger"
)
public final class App_MembersInjector implements MembersInjector<App> {
  private final Provider<Configuration> configurationProvider;

  public App_MembersInjector(Provider<Configuration> configurationProvider) {
    this.configurationProvider = configurationProvider;
  }

  public static MembersInjector<App> create(Provider<Configuration> configurationProvider) {
    return new App_MembersInjector(configurationProvider);
  }

  @Override
  public void injectMembers(App instance) {
    injectConfiguration(instance, configurationProvider.get());
  }

  public static void injectConfiguration(App instance, Configuration configuration) {
    instance.configuration = configuration;
  }
}

**Comment by mu1ex** [comment]
Closing this as its stale. Please reopen if this issue still persists
