### ISSUE TITLE
[UI Blocker]-User blocked to close CardPaymentActivity

### ISSUE THREAD

**Issue by khaledalimaf** [network-international/payment-sdk-android#4]
### User blocked to close CardPaymentActivity, moreover the AppBar is transparent 
We need more control over the activity or present activity as full with AppBar with close or back button

**STR's**

1. Initiate startActivityForResult
2. Observe the results (refer to the following screenshot) where the previous activity is still displaying and this confuse the user

<img width="382" alt="Screen Shot 2020-03-04 at 4 52 36 PM" src="https://user-images.githubusercontent.com/61741653/75968108-8e7fb300-5ed5-11ea-9fd1-a8a5bcbe3854.png">

Thanks

**Comment by mu1ex** [comment]
Hi @khaledalimaf , thanks for the feedback. We will work on getting the navigation bar for a better experience and more inline with the iOS sdk.

**Comment by khaledalimaf** [comment]
Thank you for your reply, and we will be waiting for it

**Comment by khaledalimaf** [comment]
Hi @mu1ex  
Any updates?

**Comment by mu1ex** [comment]
Hi @khaledalimaf, I have forwarded the issue to our product team. In the mean time, wouldn't the Android back button close the intent too? Apologies for the delay.

**Comment by mu1ex** [comment]
@khaledalimaf , I'm closing this issue as this is fixed in

https://github.com/network-international/payment-sdk-android/releases/tag/1.0.4

**Comment by khaledalimaf** [comment]
@mu1ex  Thank you. The screen is much better now
