### ISSUE TITLE
Failed to connect !

### ISSUE THREAD

**Issue by MahmoudZaherDeveloper** [network-international/payment-sdk-android#9]
After Import the Sample Merchant App, and run it on the real device always says : failed to connct to /10.0.2.2 (port 300) from /my device ip after 60000ms. 
Like below image

![Screenshot_20200530-232724_Furniture App](https://user-images.githubusercontent.com/50754329/83340434-32f87200-a2d8-11ea-84d5-8a5bb15a9c5d.jpg)

I think this is because that I should Run the Sample Merchant Server  as I did not know how to make it work.
Note:
I have installed Node.JS.
I did not find  config.js to configure the sample merchant server.
also I can not open http://localhost:3000.

please I need help.
Thanks in advance.

**Comment by mu1ex** [comment]
Hi @MahmoudZaherDeveloper have you tried installing the dependencies in the sample merchant server by running the command `yarn`

After the dependencies are installed you can run the server by running the command `yarn start`
